### PR TITLE
Listen and set

### PR DESCRIPTION
**Pull request by hendrikebbers**
see #3 for description

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@HanSolo @miho @hastebrot would love to get some feedback :)

**Comment by hendrikebbers** [comment]
I think the method must be renamed...

**Review by HanSolo — COMMENTED** [review]
I like the idea but I don't like the naming "onChangedAndCall" just doesn't sound correct. Unfortunately I don't have a better idea yet.

**Comment by hastebrot** [comment]
`onChangedAndCall()` looks like we should break this method into two methods. What about `replay(1).onChanged()` or `autoConnect().onChanged()`? Having only `onChanged()` would increase uniformity (which is also a problem/quality indentified in [1]). In contrast this could maybe lead to lower discoverability in the IDE (typing `on...` gives us the methods we need to handle the changes).

[1] Maier, I., & Odersky, M. (2012). Deprecating the Observer Pattern with Scala.React (No. EPFL-REPORT-176887). https://infoscience.epfl.ch/record/176887/files/DeprecatingObservers2012.pdf

---

I would probably even go further with uniformity and introduce both

~~~java
values().subscribe(newValue -> newValue)
changes().subscribe(change -> change.newValue)
~~~

i.e. instead of 

~~~java
onChanged(change -> change.newValue)
~~~

we have 

~~~java
changes().subscribe(change -> change.newValue)
~~~

An issue I didn't thought about (yet) is, how this fits into the existing `java.util.EventListener` and co.

I also like to apply this idea on e.g. `ObservableList` and use it for `additions()`, `removals()` which could both return an `Observable` (related to `CollectionChange` in #1).

**Pull request merged**
